// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMcCRo3EnffKTsjzCU_imML1-Wj5auDcw',
    appId: '1:958268921265:web:8090d15e00273aedabd990',
    messagingSenderId: '958268921265',
    projectId: 'login-1fca7',
    authDomain: 'login-1fca7.firebaseapp.com',
    storageBucket: 'login-1fca7.appspot.com',
    measurementId: 'G-YGEGMVC2C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjnx_KENqoqPf1yGIJVpUNc1sg28-kA8M',
    appId: '1:958268921265:android:de5e89798baed6e0abd990',
    messagingSenderId: '958268921265',
    projectId: 'login-1fca7',
    storageBucket: 'login-1fca7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADypDLF3LaxeiRdIfBj_Uy_GzDR3_hsjU',
    appId: '1:958268921265:ios:f506dffd5541f174abd990',
    messagingSenderId: '958268921265',
    projectId: 'login-1fca7',
    storageBucket: 'login-1fca7.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADypDLF3LaxeiRdIfBj_Uy_GzDR3_hsjU',
    appId: '1:958268921265:ios:f506dffd5541f174abd990',
    messagingSenderId: '958268921265',
    projectId: 'login-1fca7',
    storageBucket: 'login-1fca7.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMcCRo3EnffKTsjzCU_imML1-Wj5auDcw',
    appId: '1:958268921265:web:842200b97cd8008babd990',
    messagingSenderId: '958268921265',
    projectId: 'login-1fca7',
    authDomain: 'login-1fca7.firebaseapp.com',
    storageBucket: 'login-1fca7.appspot.com',
    measurementId: 'G-8DJ6C6KLBK',
  );
}
